### ISSUE TITLE
Disable issues in other rorm projects?

### ISSUE THREAD

**Issue by WebFreak001** [rorm-orm/rorm#28]
Maybe it would make sense to disable issues in the rorm subcomponents and tell users to open issues on the rorm project. This would have the benefit of having all the issues and feature requests in one place and avoids possible duplicates. Additionally users outside the maintainers of rorm might not know on which project to post issues.

Maybe rorm-lib and rorm-cli could have their own issues page, but I think just adding labels for them and putting them all here in rorm would work just as well.

**Comment by myOmikron** [comment]
I guess that would be an idea. I'll let the issues for rorm-lib and rorm-cli enabled as those are issues that doesn't belong to rorm itself.
